workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      node: 16
      java: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Install Dependencies
        script: |
          npm cache clean --force
          npm install --legacy-peer-deps
      - name: Clean Gradle Cache
        script: |
          cd android
          ./gradlew clean
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your- yksahu675@gmail.com 
