workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.yourcompany.expense"  # Replace this with your actual package name
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk
