workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.expense"  # Apna actual package name likho
    scripts:
      - name: Grant execute permission to gradlew
        script: chmod +x android/gradlew
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
