workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Install Dependencies
        script: |
          cd android
          chmod +x gradlew
          ./gradlew dependencies
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
